config/routes.rb
Rails.application.routes.draw do
  get 'admin/unauthorized'
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    get 'admin/unauthorized', to: 'admin#unauthorized'
    resources :users do
      member do
        put :approve_user
      end
      collection do
        get :pending_users
      end
    end
  end

  namespace :trader do
    get 'home', to: 'home#index'
  end

  get 'pending_approval', to: 'trader/home#pending_approval'

  resources :stocks, only: [:index]
  resources :user_stocks, only: [:create] do
    collection do
      get 'portfolio'
      post 'buy'
      post 'sell'
    end
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/trader/home_controller.rb
class Trader::HomeController < ApplicationController
  def index
    if current_user.creation_status == "pending"
      redirect_to pending_approval_path
    end
  end
end

app/helpers/trader/home_helper.rb
module Trader::HomeHelper
end

app/views/trader/home/index.html.erb
  <% if user_signed_in? %>
    <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
  <% end %>

<h1>Welcome to the Trader Home Page, <%= current_user.email %></h1>

<%= link_to 'My Portfolio', portfolio_user_stocks_path %> <br>
<%= link_to 'Stocks', stocks_path %>

<h1>Transaction History</h1>
<p>Current Balance: <%= number_to_currency(current_user.balance) %></p>


<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Stock</th>
      <th>Type</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% current_user.transactions.order(created_at: :desc).each do |transaction| %>
      <tr>
        <td><%= transaction.created_at %></td>
        <td><%= transaction.stock.name %></td>
        <td><%= transaction.transaction_type.capitalize %></td>
        <td><%= transaction.quantity %></td>
        <td><%= number_to_currency(transaction.price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/trader/home/pending_approval.html.erb
<h1>Your approval is pending</h1>
<p>Your account is pending approval. You will receive an email once your account has been approved.</p>
<%= button_to 'Logout', destroy_user_session_path, method: :delete %>

app/views/trader/home/unauthorized.html.erb
<h1>Your are not authorized to access this page.</h1>

<%= button_to 'Logout', destroy_user_session_path, method: :delete %>