config/routes.rb
Rails.application.routes.draw do
  get 'admin/unauthorized'
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    get 'admin/unauthorized', to: 'admin#unauthorized'
    resources :users do
      member do
        put :approve_user
      end
      collection do
        get :pending_users
      end
    end
  end

  namespace :trader do
    get 'home', to: 'home#index'
  end

  get 'pending_approval', to: 'trader/home#pending_approval'

  resources :stocks, only: [:index]
  resources :user_stocks, only: [:create] do
    collection do
      get 'portfolio'
      post 'buy'
      post 'sell'
    end
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_pending_approval, only: [:index]

  def index
    @stocks = Stock.all
  end

  def add
    @stock = Stock.find(params[:id])
    current_user.stocks << @stock unless current_user.stocks.include?(@stock)
    redirect_to user_stocks_portfolio_path, notice: "#{@stock.name} was added to your portfolio."
  end

  private
  
  def check_pending_approval
    if current_user.user_type == 'trader' && current_user.creation_status == 'pending'
      redirect_to pending_approval_path, alert: 'Your account is pending approval. Please wait until your account is approved to access the stock list.'
    end
  end
end

app/views/stocks/index.html.erb
<!-- app/views/stocks/index.html.erb -->

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ticker</th>
      <th>Price</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.ticker %></td>
        <td><%= number_to_currency(stock.price) %></td>
        <td>
          <% unless current_user.stocks.include?(stock) %>
            <%= button_to 'Add to Portfolio', user_stocks_path(stock_id: stock.id), method: :post, class: 'btn btn-primary' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Home', trader_home_path %>
<%= link_to 'My Portfolio', portfolio_user_stocks_path %>
