config/routes.rb
Rails.application.routes.draw do
  get 'admin/unauthorized'
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    get 'admin/unauthorized', to: 'admin#unauthorized'
    resources :users do
      member do
        put :approve_user
      end
      collection do
        get :pending_users
      end
    end
  end

  namespace :trader do
    get 'home', to: 'home#index'
  end

  get 'pending_approval', to: 'trader/home#pending_approval'

  resources :stocks, only: [:index]
  resources :user_stocks, only: [:create] do
    collection do
      get 'portfolio'
      post 'buy'
      post 'sell'
    end
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_pending_approval, only: [:portfolio, :create]

  def create
    stock = Stock.find(params[:stock_id])
    
    if current_user.stocks.include?(stock)
      redirect_to stocks_path, alert: 'Stock already in your portfolio.'
    else
      current_user.stocks << stock
      redirect_to user_stocks_path, notice: 'Stock was successfully added to your portfolio.'
    end
  end

  def portfolio
    @stocks = current_user.stocks
  end

  def buy
    stock = Stock.find(params[:stock_id])
    user_stock = current_user.user_stocks.find_or_initialize_by(stock: stock)
    quantity = params[:quantity].to_i
    total_price = stock.price * quantity

    if total_price <= current_user.balance
      ActiveRecord::Base.transaction do
        current_user.balance -= total_price
        user_stock.quantity += quantity
        user_stock.save!
        current_user.save!

        Transaction.create!(
          user: current_user,
          stock: stock,
          transaction_type: 'buy',
          quantity: quantity,
          price: total_price
        )
      end

      redirect_to portfolio_user_stocks_path, notice: "Successfully bought #{quantity} shares of #{stock.name}."
    else
      redirect_to portfolio_user_stocks_path, notice: "You don't have enough balance to buy #{quantity} shares of #{stock.name}."
    end
  end

  def sell
    stock = Stock.find(params[:stock_id])
    user_stock = current_user.user_stocks.find_by(stock: stock)
    quantity = params[:quantity].to_i
    total_price = stock.price * quantity
  
    if user_stock && user_stock.quantity >= quantity
      ActiveRecord::Base.transaction do
        current_user.balance += total_price
        user_stock.quantity -= quantity
        user_stock.save!
        current_user.save!
  
        Transaction.create!(
          user: current_user,
          stock: stock,
          transaction_type: 'sell',
          quantity: quantity,
          price: total_price
        )
      end
  
      redirect_to portfolio_user_stocks_path, notice: "Successfully sold #{quantity} shares of #{stock.name}."
    else
      redirect_to portfolio_user_stocks_path, notice: "You don't have enough shares of #{stock.name} to sell #{quantity}."
    end
  end

  private

  def check_pending_approval
    if current_user.user_type == 'trader' && current_user.creation_status == 'pending'
      redirect_to pending_approval_path, alert: 'Your account is pending approval. Please wait until your account is approved to access the stock list.'
    end
  end
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/user_stocks/create.html.erb
<h1>UserStocks#create</h1>
<p>Find me in app/views/user_stocks/create.html.erb</p>

app/views/user_stocks/portfolio.html.erb
<h1>My Portfolio</h1>
<h4><%= current_user.email %></h4>
<%= link_to 'Home', trader_home_path %> <br>
<%= link_to 'Stocks', stocks_path %>

<p>Current Balance: <%= number_to_currency(current_user.balance) %></p>

<% if notice %>
    <p class="notice"><%= notice %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ticker</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @stocks.each do |stock| %>
      <% user_stock = current_user.user_stocks.find_by(stock: stock) %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.ticker %></td>
        <td><%= number_to_currency(stock.price) %></td>
        <td><%= user_stock.quantity %></td>
        <td>
          <%= form_with url: buy_user_stocks_path(stock_id: stock.id), method: :post, local: true do |form| %>
            <%= form.number_field :quantity, value: 1, min: 1 %>
            <%= form.submit 'Buy' %>
          <% end %>

          <%= form_with url: sell_user_stocks_path(stock_id: stock.id), method: :post, local: true do |form| %>
            <%= form.number_field :quantity, value: 1, min: 1, max: user_stock ? user_stock.quantity : 0 %>
            <%= form.submit 'Sell' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>