config/routes.rb
Rails.application.routes.draw do
  get 'admin/unauthorized'
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    get 'admin/unauthorized', to: 'admin#unauthorized'
    resources :users do
      member do
        put :approve_user
      end
      collection do
        get :pending_users
      end
    end
  end

  namespace :trader do
    get 'home', to: 'home#index'
  end

  get 'pending_approval', to: 'trader/home#pending_approval'

  resources :stocks, only: [:index]
  resources :user_stocks, only: [:create] do
    collection do
      get 'portfolio'
      post 'buy'
      post 'sell'
    end
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  USER_TYPES = %w[trader admin].freeze
  CREATION_STATUSES = %w[pending approved].freeze

  validates :user_type, inclusion: { in: USER_TYPES }
  validates :creation_status, inclusion: { in: CREATION_STATUSES }

  before_validation :set_default_user_type, on: :create
  before_validation :set_default_creation_status, on: :create

  after_create :send_appropriate_email

  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  has_many :transactions, dependent: :destroy

  def trader?
    user_type == 'trader'
  end

  def admin?
    user_type == 'admin'
  end

  private

  def set_default_user_type
    self.user_type ||= 'trader'
  end

  def set_default_creation_status
    self.creation_status ||= 'pending'
  end

  def send_appropriate_email
    if self.creation_status == 'pending'
      send_pending_signup_email
    elsif self.creation_status == 'approved'
      send_approval_email
    end
  end

  def send_pending_signup_email
    UserMailer.with(user: self).pending_signup_email.deliver_now
  end

  def send_approval_email
    UserMailer.with(user: self).approval_email.deliver_now
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authorize_admin!
  before_action :set_user, only: [:edit, :update, :destroy, :show, :approve_user]
    
  
  def index
    @users = User.where(creation_status: 'approved').where.not(user_type: 'admin')

    @transactions = Transaction.includes(:user, :stock).order(created_at: :desc)
  end

  def show
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    @user.creation_status = "approved"
    if @user.save
      redirect_to admin_users_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: 'User was successfully deleted.'
  end

  def pending_users
    @users = User.where(creation_status: "pending").where.not(user_type: 'admin')
  end

  def approve_user
    if @user.update(creation_status: params[:status])
      UserMailer.with(user: @user).approval_email.deliver_now if @user.creation_status == 'approved'
      redirect_to pending_users_admin_users_path, notice: 'User status updated successfully.'
    else
      redirect_to pending_users_admin_users_path, alert: 'Failed to update user status.'
    end
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :user_type, :creation_status)
  end

  def authorize_admin!
    redirect_to admin_unauthorized_path unless current_user.admin?
  end

end
  

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    pending_approval_path
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with model: @user, url: admin_user_path(@user), local: true do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit 'Update User' %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= link_to 'Back to User List', admin_users_path %>

<h1>Edit User</h1>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Welcome Admin!</h1>

<%= button_to 'Logout', destroy_user_session_path, method: :delete %>

<h2>Users</h2>
<%= link_to 'New User', new_admin_user_path %><br>
<%= link_to 'Pending Users', pending_users_admin_users_path	 %>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>User Type</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      
        <tr>
          <td><%= user.email %></td>
          <td><%= user.user_type %></td>
          <td><%= link_to 'Details', admin_user_path(user) %></td>
          <td><%= button_to 'Delete', admin_user_path(user), method: :delete %></td>
        </tr>
      
    <% end %>
  </tbody>
</table>

<h3>Transactions of Users</h3>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>User</th>
      <th>Stock</th>
      <th>Type</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= transaction.user.email %></td>
        <td><%= transaction.stock.name %></td>
        <td><%= transaction.transaction_type.capitalize %></td>
        <td><%= transaction.quantity %></td>
        <td><%= number_to_currency(transaction.price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<%= link_to 'Back to User List', admin_users_path %>

<h1>New User</h1>

<%= form_with model: @user, url: admin_users_path, local: true do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit 'Create User' %>
  </div>
<% end %>

app/views/admin/users/pending_users.html.erb
<%= link_to 'Back to All Users', admin_users_path %>
<h1>Pending Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Creation Status</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.creation_status %></td>
        <td>
          <%= form_with url: approve_user_admin_user_path(user), method: :put, local: true do |form| %>
            <%= hidden_field_tag :id, user.id %>
            <%= hidden_field_tag :status, 'approved' %>
            <%= submit_tag 'Approve' %>
          <% end %>
        </td>
        <td><%= button_to 'Delete', admin_user_path(user), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/show.html.erb
<%= link_to 'Back to User List', admin_users_path %>
<h1>User Details</h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>User Type:</strong>
  <%= @user.user_type %>
</p>

<p>
  <%= link_to 'Edit Details', edit_admin_user_path(@user) %>
</p>